name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    name: Test (${{ matrix.build_type }})

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Configure and Build
      run: |
        mkdir build-${{ matrix.build_type }}
        cd build-${{ matrix.build_type }}
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=ON
        make

    - name: Run tests
      run: |
        cd build-${{ matrix.build_type }}
        ./chip8-tests